doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
    
framework:
    cache:
        pools:
            doctrine_result_cache_pool:  # Renommé
                adapter: cache.app
            doctrine_system_cache_pool:  # Renommé
                adapter: cache.system

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine_system_cache_pool  # Utilisation du nouveau nom
            result_cache_driver:
                type: pool
                pool: doctrine_result_cache_pool  # Utilisation du nouveau nom
