security:
    # Configuration pour le hashage de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs d'utilisateurs
    providers:
        # Utilisé pour recharger l'utilisateur à partir de la session
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuth
            entry_point: App\Security\LoginFormAuth
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: /home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôles d'accès par rôle
    access_control:
        # Accès spécifique pour chaque rôle
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/artist/dashboard, roles: ROLE_ARTIST }
        - { path: ^/producteur/dashboard, roles: ROLE_PRODUCTEUR }
        - { path: ^/beatmaker/dashboard, roles: ROLE_BEATMAKER }
        - { path: ^/musicien/dashboard, roles: ROLE_MUSICIEN }
        - { path: ^/collaborations, roles: IS_AUTHENTICATED_FULLY }
        # Accès aux collaborations pour tous les rôles
        - { path: ^/collaborations, roles: [ROLE_ARTIST, ROLE_PRODUCTEUR, ROLE_BEATMAKER, ROLE_MUSICIEN, ROLE_ADMIN] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
